export const cities = [
  { city_name: "Bengaluru" },
  { city_name: "Mysuru" },
  { city_name: "Hubballi" },
  { city_name: "Belagavi" },
  { city_name: "Haveri" },
  { city_name: "Davanagere" },
  { city_name: "Shivamogga" },
  { city_name: "Tumakuru" },
  { city_name: "Dharwad" },
  { city_name: "Raichur" },
  { city_name: "Hassan" },
  { city_name: "Kolar" },
  { city_name: "Udupi" },
  { city_name: "Ramanagara" },
  { city_name: "Gadag" },
  { city_name: "Madikeri" },
  { city_name: "Sirsi" },
  { city_name: "Tiptur" },
  { city_name: "Bhadravati" },
  { city_name: "Tumukuru" },
];
